trigger:
  - main
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:

- job: backend
  displayName: Backend_Build 
  workspace:
    clean: all
  # variables:
  #   - group: Eat_Well_Variable_Group
  # steps:
  #   - template: devops/yaml/backend.yml
 