trigger:
  paths:
    include: # Include!
    - 'src/api/*'
  
  
pool:
  vmImage: 'windows-latest'

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: stageName
    value: "First stage"

jobs:

- job: Backend
  displayName: Backend_Build 
  workspace:
    clean: all
  # variables:
  #   - group: Eat_Well_Variable_Group
  steps:
    - template: ../devops/yaml/backend.yml
 