trigger:
  paths:
    include: # Include!
    - 'src/api/*'
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  stageName: "First stage" 
  solution: '**\*.sln'
  buildPlatform: 'Any CPU'

jobs:

- job: Backend
  displayName: Backend_Build 
  workspace:
    clean: all
  # variables:
  #   - group: Eat_Well_Variable_Group
  steps:
    - template: ../devops/yaml/backend.yml
 